-- 1. Tabla de Usuarios (Director, Docentes y Auxiliares)
create table if not exists usuarios (
  id text primary key,
  usuario text unique not null,
  clave text not null,
  rol text not null,
  nombre text not null,
  aulas_asignadas jsonb default '[]'::jsonb
);

-- 2. Tabla de Estudiantes
create table if not exists estudiantes (
  id text primary key,
  dni text,
  name text not null,
  grade text not null,
  section text not null,
  phone text
);

-- 3. Tabla de Asistencias
create table if not exists asistencias (
  id bigint generated by default as identity primary key,
  fecha text not null,
  estudiante_id text not null,
  estudiante_nombre text,
  seccion text,
  estado text,
  registrado_por text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 4. Desactivar RLS para que cualquier celular o PC sincronice libremente
alter table usuarios disable row level security;
alter table estudiantes disable row level security;
alter table asistencias disable row level security;
